name: SOOS SBOM GitHub Actions 02
on: [push]
jobs:
  soos_sbom_scan:
    name: SOOS SBOM Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SBOM Scan
        uses: soos-io/soos-sbom-github-action@b39b0d6af2d627f691f347f771854b14dc9d366c
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          api_url: 'https://qa-api.soos.io/api/'
          project_name: "sbom-githubActions-with-SBOM-Path"
          sbom_path: SPDX
          sbom_version: 1.0.11-pre.2 
          log_level: DEBUG
          export_format: SARIF
          export_file_type: test
        
      # Cargar el directorio generado como artefacto
      - uses: actions/upload-artifact@v4
        with:
          name: sast-analysis-output
          path: |
              ${{ github.workspace }}/*.cdx.json
              ${{ github.workspace }}/*.cdx.xml
              ${{ github.workspace }}/*.spdx.json
              ${{ github.workspace }}/*.spdx.txt
              ${{ github.workspace }}/*.sarif.json
              ${{ github.workspace }}/*.csafvex.json
              ${{ github.workspace }}/*.sooslicenses.hmtl
              ${{ github.workspace }}/*.sooslicenses.csv
              ${{ github.workspace }}/*.soospackages.hmtl
              ${{ github.workspace }}/*.soospackages.csv
              ${{ github.workspace }}/*.soosvulnerabilities.hmtl
              ${{ github.workspace }}/*.soosvulnerabilities.csv
              ${{ github.workspace }}/*.soosissues.hmtl
              ${{ github.workspace }}/*.soosissues.csv
