name: SOOS SBOM GitHub Actions 01
on: [push]
jobs:
  soos_sbom_scan:
    name: SOOS SBOM Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SBOM Scan
        uses: soos-io/soos-sbom-github-action@bdbfacf7c82cf67bed99f32be04f282b2140f139
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "GitHubActions-SBOM-4"
          api_url: 'https://qa-api.soos.io/api/' 
          sbom_path: "./"
          log_level: DEBUG
          sbom_version: "1.0.1-pre.4"
          directories_to_exclude: "SPDX/**, one file/surrealdb_v1.5.4.rust.cdx.json"
          #files_to_exclude: "SPDX/camaleon cms_v2.8.0.ruby.spdx.json"

