name: SOOS SBOM GitHub Actions 02
on: [push]
jobs:
  soos_sbom_scan:
      permissions:
        security-events: write # for uploading code scanning alert info
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      name: SOOS SBOM Scan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - uses: actions/checkout@master
        - name: Run SOOS SBOM Scan
          uses: soos-io/soos-sbom-github-action@v1
          with:
            client_id: ${{ secrets.SOOS_CLIENT_ID }} 
            api_key: ${{ secrets.SOOS_API_KEY }}
            api_url: 'https://qa-api.soos.io/api/'
            project_name: "SBOM-githubActions"
            sbom_path: "./"
            sbom_version: 1.0.13-pre.2
            log_level: DEBUG
            export_format: sarif
            export_file_type: json
            output_directory: output
    
        
        # Cargar el directorio generado como artefacto
        - uses: actions/upload-artifact@v4
          with:
            name: sbom-analysis-output
            path: |
                ${{ github.workspace }}/output/*.cdx.json
                ${{ github.workspace }}/output/*.cdx.xml
                ${{ github.workspace }}/output/*.spdx.json
                ${{ github.workspace }}/output/*.spdx.txt
                ${{ github.workspace }}/output/*.sarif.json
                ${{ github.workspace }}/output/*.csafvex.json
                ${{ github.workspace }}/output/*.sooslicenses.html
                ${{ github.workspace }}/output/*.sooslicenses.csv
                ${{ github.workspace }}/output/*.soospackages.html
                ${{ github.workspace }}/output/*.soospackages.csv
                ${{ github.workspace }}/output/*.soosvulnerabilities.html
                ${{ github.workspace }}/output/*.soosvulnerabilities.csv
                ${{ github.workspace }}/output/*.soosissues.html
                ${{ github.workspace }}/output/*.soosissues.csv

        - name: Get SARIF file
          id: get-sarif
          run: |
            FILE=$(ls ${{ github.workspace }}/output/*.sarif.json | head -n 1) 
            echo "sarif_file=$FILE" >> $GITHUB_ENV

        #- name: Upload SOOS SARIF Report
        #  uses: github/codeql-action/upload-sarif@v3
        #  with:
        #      sarif_file: ${{ env.sarif_file }}
