name: SOOS SBOM GitHub Actions 02
on: [push]
jobs:
  soos_sbom_scan:
    name: SOOS SBOM Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SBOM Scan
        uses: soos-io/soos-sbom-github-action@v1.0.5
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "sbom-githubActions-13"
          api_url: 'https://qa-api.soos.io/api/'
          sbom_path: "SPDX/camaleon_cms_v2.8.0.ruby.spdx.json"
          build_version: 4.3.1
          on_failure: "FAIL_THE_BUILD"

