name: SOOS SBOM GitHub Actions 02
on: [push]
jobs:
  soos_sbom_scan:
    name: SOOS SBOM Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SBOM Scan
        uses: soos-io/soos-sbom-github-action@b6d8e8427e17895fcaf87a8fb5c8bd35808d67da
        with:
          client_id: ${{ secrets.SOOS_QA_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_QA_API_KEY }}
          project_name: "sbom-githubActions-08"
          api_url: 'https://qa-api.soos.io/api/'
          sbom_path: 'spdx/camaleon cms_v2.8.0.ruby.spdx.json'
          sbom_version: 1.0.5-pre.1
        

