name: SOOS SBOM GitHub Actions 01
on: [push]
jobs:
  soos_sbom_scan:
    name: SOOS SBOM Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SBOM Scan
        uses: soos-io/soos-sbom-github-action@bdbfacf7c82cf67bed99f32be04f282b2140f139
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "GitHubActions-SBOM"
          api_url: 'https://qa-api.soos.io/api/'
          sbom_path: "cyclonedx/alpine-baselayout.cdx.json"
          log_level: DEBUG
          sbom_version: "1.0.1-pre.4"
          #directories_to_exclude: "**/subfolder2/**"
          #files_to_exclude: "**/next_v14.2.13.npm.spdx.json"
