name: SOOS SBOM GitHub Actions 02
on: [push]
jobs:
  soos_sbom_scan:
    name: SOOS SBOM Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SBOM Scan
        uses: soos-io/soos-sbom-github-action@v1
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "sbom-githubActions-test"
          api_url: 'https://qa-api.soos.io/api/'
          sbom_path: "./"
          build_version: 4.3.1
          sbom_version: latest
          log_level: debug
          files_to_exclude: "**/Flutter/flutter_Downloader_v1.11.0.dart.cdx.json"

